// What the oracles in this file decide.
//
// Identification is a statistical estimate from a noisy record, so the bounds
// here are derived from the noise that generated the record rather than fitted
// to the answer that came back:
//
//  * Where a configuration is out of domain the construction is REFUSED with the
//    enumerator that names the cause. Where it is degenerate but in domain -- a
//    zero-confidence prior, a non-finite regressor -- the update is a no-op and
//    the parameters stay BITWISE at their initial values.
//  * Where a case name promises identified coefficients, the coefficients are
//    asserted, against the parameter standard error the noise magnitude, the
//    sample count and the accumulated regressor second moment imply, times a
//    stated confidence multiplier. Not against a band two decades looser.
//  * Where a fit metric is asserted, its floor is derived from the noise model
//    the record was generated under. That floor differs between the two model
//    families and the difference is real: the recursive record carries its noise
//    as PROCESS noise, so a free-run simulation amplifies it by one over the
//    square root of one minus the pole squared, while the state-space records
//    carry it as measurement noise on the output alone, which a free run does
//    not amplify at all.
//  * The subspace method returns a SIMILARITY-TRANSFORMED realization, so its
//    coefficients cannot be compared with the ones that generated the data. The
//    eigenvalue and the direct-current gain can, and those are what is asserted.
//  * The companion superdiagonal is exactly one. It is structural, not merely
//    finite, and if it is not one the initialization loop the case exists to
//    exercise is wrong.
//
// What they deliberately do not decide. The rank-deficient batch case does not
// pin which member of the solution set the decomposition selects: measured, it
// is not the minimum-norm one, so naming that would state something false. What
// it asserts instead is the property every member shares, that the fitted model
// reproduces the record. And no case asserts a rank threshold for a random
// Hankel matrix; deriving one is separate numerical work.

#include "hardening_helpers.h"

#include "ctrlpp/sysid/rls.h"
#include "ctrlpp/sysid/batch_arx.h"
#include "ctrlpp/sysid/moesp.h"
#include "ctrlpp/sysid/recursive_arx.h"

#include <catch2/catch_test_macros.hpp>

#include <Eigen/Dense>

#include <cmath>
#include <limits>
#include <random>

namespace {

constexpr double eps = std::numeric_limits<double>::epsilon();

/// Noise standard deviations of the generated records, named so the bounds below
/// read as functions of the noise rather than as constants.
constexpr double noise_sd_fine = 0.001;
constexpr double noise_sd_coarse = 0.01;

/// Confidence multiplier on every standard-error bound in this file.
///
/// Three standard errors. The generators are seeded, so nothing here is flaky
/// and the multiplier is not protecting against a rerun -- it is the statement
/// that the assertion is about the estimator's sampling distribution and not
/// about this one realization of it. Each use records the realized ratio.
constexpr double confidence_multiplier = 3.0;

/// Relative allowance on a residual-norm bound built from a finite record.
///
/// A sum of n squared residuals has a relative spread of the square root of two
/// over n about its expectation, so a floor derived from the noise standard
/// deviation is met only to within that spread. Carried at the same three
/// standard errors as the parameter bounds.
auto residual_norm_allowance(int samples) -> double
{
    return confidence_multiplier * std::sqrt(2.0 / static_cast<double>(samples));
}

/// Index of the largest step down between consecutive singular values.
///
/// A record generated by a system of order p has p singular values well above
/// the noise and the rest at it, so the largest step sits at index p - 1. A
/// record with no system has no such step at the front. Comparing the routine's
/// own numbers with each other needs no threshold.
auto largest_singular_value_gap(Eigen::VectorXd const& sv) -> Eigen::Index
{
    Eigen::Index best = 0;
    double best_ratio = 0.0;
    for (Eigen::Index k = 0; k + 1 < sv.size(); ++k) {
        double const ratio = sv(k) / sv(k + 1);
        if (ratio > best_ratio) {
            best_ratio = ratio;
            best = k;
        }
    }
    return best;
}

}

// ── RLS hardening ──────────────────────────────────────────────────────────────

TEST_CASE("RLS with singular covariance P0", "[rls][hardening][negative]")
{
    ctrlpp::rls_config<double, 2> cfg;
    cfg.P0 = ctrlpp::Matrix<double, 2, 2>::Zero();
    // Singular and entirely well-posed: every entry is finite, so the
    // configuration validation accepts it. Finiteness is the domain condition
    // and definiteness is not; rejecting a singular P0 would refuse a starting
    // point that says only "I am certain of these parameters".
    auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create(cfg));

    Eigen::Vector2d phi;
    phi << 1.0, 0.5;
    REQUIRE(estimator.update(1.0, phi).has_value());

    // A zero-confidence prior makes the gain P phi / (lambda + phi' P phi) an
    // exact zero vector, so the update is a no-op and the parameters stay bitwise
    // at their initial value. That is the required property of "I am certain of
    // these parameters"; finiteness held for a gain that had moved them anywhere
    // at all. The file already uses this bitwise form for the degenerate-regressor
    // case below.
    auto theta = estimator.parameters();
    REQUIRE(theta(0) == 0.0);
    REQUIRE(theta(1) == 0.0);

    // And it stays a no-op: a zero covariance has nothing to shrink, so no later
    // sample re-opens the estimator.
    REQUIRE(estimator.update(2.0, phi).has_value());
    REQUIRE(estimator.parameters()(0) == 0.0);
    REQUIRE(estimator.parameters()(1) == 0.0);
}

TEST_CASE("RLS rejects an out-of-domain forgetting factor", "[rls][hardening][negative]")
{
    SECTION("zero")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.lambda = 0.0;

        // The forgetting factor is the divisor of the covariance update
        // P <- (P - k phi^T P) / lambda, so a zero factor divides by zero on the
        // very first sample: every entry of P becomes non-finite, the gain
        // formed from it is non-finite, and every parameter estimate afterwards
        // is meaningless -- while the boolean update return still reports
        // success. Rejecting here is what stops that.
        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::non_positive_forgetting_factor);
    }

    SECTION("negative")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.lambda = -0.5;

        // The same division, with the sign flipped: it negates a positive
        // semidefinite covariance, so every later gain points against the error
        // rather than along it. Finite arithmetic, no diagnostic, wrong answers.
        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::non_positive_forgetting_factor);
    }

    SECTION("above unity")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.lambda = 1.5;

        // A separate enumerator because it is a separate kind of fault: the
        // arithmetic here is well defined and the consequence is silent rather
        // than explosive. Dividing by a factor above one deflates the covariance
        // faster than the measurement update alone, so the gain collapses toward
        // zero and the estimator stops adapting. Exponential forgetting is
        // defined on (0, 1], which is what this rejection enforces.
        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::forgetting_factor_above_unity);
    }

    SECTION("unity is accepted -- it is ordinary recursive least squares")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.lambda = 1.0;

        CHECK(ctrlpp::rls<double, 2>::create(cfg).has_value());
    }
}

TEST_CASE("RLS rejects a non-finite initial covariance and a degenerate bound", "[rls][hardening][negative]")
{
    SECTION("non-finite initial covariance")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.P0 = ctrlpp::test::nan_matrix<double, 2, 2>();

        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::non_finite_initial_covariance);
    }

    SECTION("zero covariance bound")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.cov_upper_bound = 0.0;

        // The clamp rescales P by bound*NP/trace once the trace exceeds the
        // bound, so a zero bound drives the covariance to exactly zero on the
        // first sample and the parameters never move again.
        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::non_positive_covariance_bound);
    }

    SECTION("non-finite covariance bound")
    {
        ctrlpp::rls_config<double, 2> cfg;
        cfg.cov_upper_bound = std::numeric_limits<double>::infinity();

        // An infinite bound disables the clamp the field exists to impose: the
        // trace can never exceed it, so the covariance is unbounded in a type
        // whose stated contract is that it is bounded.
        const auto rejected = ctrlpp::rls<double, 2>::create(cfg);

        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_error::non_positive_covariance_bound);
    }
}

TEST_CASE("recursive_arx forwards the estimator's configuration rejection", "[rls][hardening][negative]")
{
    ctrlpp::rls_config<double, 3> cfg;
    cfg.lambda = 0.0;

    const auto rejected = ctrlpp::recursive_arx<double, 2, 1>::create(cfg);

    REQUIRE_FALSE(rejected.has_value());
    CHECK(rejected.error() == ctrlpp::rls_error::non_positive_forgetting_factor);
}

TEST_CASE("RLS refuses a non-finite operand without touching its memory",
          "[rls][hardening][negative]")
{
    SECTION("a non-finite regressor")
    {
        auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create());
        const auto P_before = estimator.covariance();

        auto phi = ctrlpp::test::nan_vector<double, 2>();
        const auto rejected = estimator.update(1.0, phi);

        // The refusal now names its cause. It used to be inferred from a
        // degenerate denominator and reported as a bare false the wrapper could
        // discard: the regressor reaches the parameters through the gain and the
        // covariance through the rank one update, so it destroys both, and that
        // is a different subsystem's fault from a bad output sample.
        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_update_error::non_finite_regressor);

        // Bitwise, because a refused cycle performs no arithmetic on either.
        CHECK(estimator.parameters()(0) == 0.0);
        CHECK(estimator.parameters()(1) == 0.0);
        CHECK(estimator.covariance() == P_before);
    }

    SECTION("a non-finite observation")
    {
        auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create());
        const auto P_before = estimator.covariance();

        Eigen::Vector2d phi;
        phi << 1.0, 0.5;
        const auto rejected =
            estimator.update(std::numeric_limits<double>::quiet_NaN(), phi);

        // This one was ACCEPTED before the conversion, and silently: the output
        // sample enters only the prediction error, so the denominator stayed
        // finite, the guard passed, and the parameters became non-finite while
        // the update reported success. Nothing downstream could tell.
        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_update_error::non_finite_observation);
        CHECK(estimator.parameters()(0) == 0.0);
        CHECK(estimator.parameters()(1) == 0.0);
        CHECK(estimator.covariance() == P_before);
    }
}

TEST_CASE("RLS refuses a denominator with no significant digits left in it",
          "[rls][hardening][negative]")
{
    // The floor the refusal uses is derived from the operands that formed the
    // denominator, and both directions of an absolute floor's failure are
    // reachable through the public surface.

    SECTION("a well-posed update far below unit scale is ACCEPTED")
    {
        // The forgetting factor and the covariance are both tiny, so the
        // denominator is about 1e-15 -- below the absolute floor this replaces,
        // which would have refused it. Nothing is ill conditioned: the gain is
        // the covariance-weighted regressor over a denominator of the same
        // magnitude, so it is of order one.
        ctrlpp::rls_config<double, 2> cfg;
        cfg.lambda = 1e-15;
        cfg.P0 = ctrlpp::Matrix<double, 2, 2>::Identity() * 1e-12;
        auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create(cfg));

        Eigen::Vector2d phi;
        phi << 1e-3, 0.0;

        const auto applied = estimator.update(1.0, phi);
        REQUIRE(applied.has_value());
        REQUIRE(estimator.parameters().allFinite());
        // The update did something: a refused cycle would have left the
        // parameters bitwise at zero.
        REQUIRE(estimator.parameters()(0) != 0.0);
    }

    SECTION("reciprocal covariance and regressor scales remain representable")
    {
        for(int exponent = 40; exponent <= 200; exponent += 20)
        {
            const double regressor_scale = std::pow(10.0, exponent);
            const double covariance_scale = std::pow(10.0, -exponent);

            ctrlpp::rls_config<double, 2> cfg;
            cfg.lambda = 1.0;
            cfg.P0 =
                ctrlpp::Matrix<double, 2, 2>::Identity() * covariance_scale;
            auto estimator =
                ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create(cfg));

            Eigen::Vector2d phi;
            phi << regressor_scale, regressor_scale;

            const auto applied = estimator.update(1.0, phi);
            CAPTURE(exponent);
            REQUIRE(applied.has_value());
            REQUIRE(estimator.parameters().allFinite());
            REQUIRE(estimator.covariance().allFinite());
        }
    }

    SECTION("a cancelled denominator far above unit scale is REFUSED")
    {
        // Definiteness of the initial covariance is deliberately not a
        // construction condition -- a caller may pose any finite starting point --
        // so an indefinite one is reachable, and with it a quadratic form that
        // cancels. Here phi' P phi is two terms of magnitude 1e20 differing in
        // the last few digits, so the residue is about 1e4 and carries no
        // significant digits at all. An absolute floor sees 1e4, calls it healthy
        // and divides a gain by rounding noise; the derived floor is 2.2e5 at
        // this operand scale and refuses.
        ctrlpp::rls_config<double, 2> cfg;
        cfg.P0 = ctrlpp::Matrix<double, 2, 2>::Zero();
        cfg.P0(0, 0) = 1e20;
        cfg.P0(1, 1) = -1e20;
        auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create(cfg));

        Eigen::Vector2d phi;
        phi << 1.0, 0.9999999999999999;

        const auto rejected = estimator.update(1.0, phi);
        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_update_error::denominator_below_resolution);
        CHECK(estimator.parameters()(0) == 0.0);
        CHECK(estimator.parameters()(1) == 0.0);
    }

    SECTION("a covariance that has stopped being one is REFUSED by name")
    {
        // The same indefinite starting point with a regressor that does not
        // cancel: the quadratic form is a large NEGATIVE number, so the
        // denominator is negative by far more than its own resolution. That is
        // not a resolution question, it is the covariance having lost positive
        // semidefiniteness, and a gain formed from it would point against the
        // prediction error -- so it gets its own enumerator.
        ctrlpp::rls_config<double, 2> cfg;
        cfg.P0 = ctrlpp::Matrix<double, 2, 2>::Zero();
        cfg.P0(0, 0) = 1.0;
        cfg.P0(1, 1) = -1e6;
        auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create(cfg));

        Eigen::Vector2d phi;
        phi << 0.0, 1.0;

        const auto rejected = estimator.update(1.0, phi);
        REQUIRE_FALSE(rejected.has_value());
        CHECK(rejected.error() == ctrlpp::rls_update_error::indefinite_covariance);
    }
}

TEST_CASE("RLS rejects a non-finite update candidate without committing it",
          "[rls][hardening][negative]")
{
    ctrlpp::rls_config<double, 1> config;
    config.P0 << 1.0;
    config.lambda = 1.0;
    auto estimator =
        ctrlpp::test::constructed(ctrlpp::rls<double, 1>::create(config));
    ctrlpp::Vector<double, 1> regressor;
    regressor << 1.0;

    REQUIRE(estimator.update(
        std::numeric_limits<double>::max(), regressor).has_value());
    auto const parameters_before = estimator.parameters();
    auto const covariance_before = estimator.covariance();

    auto result = estimator.update(
        -std::numeric_limits<double>::max(), regressor);
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error() == ctrlpp::rls_update_error::non_finite_result);
    CHECK(estimator.parameters() == parameters_before);
    CHECK(estimator.covariance() == covariance_before);
}

TEST_CASE("recursive_arx forwards a refused sample instead of swallowing it",
          "[recursive_arx][hardening][negative]")
{
    auto arx = ctrlpp::test::constructed(ctrlpp::recursive_arx<double, 2, 1>::create());

    REQUIRE(arx.update(1.0, 0.5).has_value());
    const auto theta_before = arx.parameters();

    // The wrapper used to call the estimator and discard its answer, so a
    // refused sample was swallowed here and no caller could learn the model had
    // stopped moving. It now forwards the estimator's own enumerator rather than
    // restating it under a second name.
    const auto rejected = arx.update(std::numeric_limits<double>::quiet_NaN(), 0.5);
    REQUIRE_FALSE(rejected.has_value());
    CHECK(rejected.error() == ctrlpp::recursive_arx_update_error::non_finite_observation);
    CHECK(arx.parameters() == theta_before);

    // And the refused sample did not enter the regressor history either. That is
    // the half a forwarded error alone would not give: recording it would have
    // poisoned every regressor built afterwards, so the poison would latch in the
    // wrapper after the estimator had correctly declined it.
    REQUIRE(arx.update(0.8, 0.3).has_value());
    CHECK(arx.parameters().allFinite());
}

TEST_CASE("recursive_arx refuses a non-finite input without poisoning its history",
          "[recursive_arx][hardening][negative]")
{
    auto tested = ctrlpp::test::constructed(ctrlpp::recursive_arx<double, 2, 1>::create());
    auto reference = ctrlpp::test::constructed(ctrlpp::recursive_arx<double, 2, 1>::create());

    REQUIRE(tested.update(1.0, 0.5).has_value());
    REQUIRE(reference.update(1.0, 0.5).has_value());

    const auto rejected =
        tested.update(0.8, std::numeric_limits<double>::quiet_NaN());
    REQUIRE_FALSE(rejected.has_value());
    CHECK(rejected.error() == ctrlpp::recursive_arx_update_error::non_finite_input);
    CHECK(tested.parameters() == reference.parameters());
    CHECK(tested.covariance() == reference.covariance());

    REQUIRE(tested.update(0.7, 0.3).has_value());
    REQUIRE(reference.update(0.7, 0.3).has_value());
    CHECK(tested.parameters() == reference.parameters());
    CHECK(tested.covariance() == reference.covariance());
}

TEST_CASE("RLS identifies known first-order system", "[rls][hardening][convergence]")
{
    constexpr std::size_t NP = 2;
    auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, NP>::create());

    std::mt19937 gen(42);
    std::normal_distribution<double> noise(0.0, noise_sd_fine);
    std::uniform_real_distribution<double> input(-1.0, 1.0);

    Eigen::Vector2d true_theta;
    true_theta << 0.8, 0.5; // y = 0.8*x1 + 0.5*x2

    constexpr int samples = 500;
    Eigen::Matrix2d second_moment = Eigen::Matrix2d::Zero();

    for (int i = 0; i < samples; ++i) {
        Eigen::Vector2d phi;
        phi << input(gen), input(gen);
        double y = true_theta.dot(phi) + noise(gen);
        REQUIRE(estimator.update(y, phi).has_value());
        second_moment += phi * phi.transpose();
    }

    // The estimate's standard error is the noise standard deviation times the
    // square root of the corresponding diagonal entry of the inverse regressor
    // second moment -- the textbook least-squares covariance, which the recursion
    // reaches at unit forgetting. That is about 8e-5 for both parameters here,
    // against the 0.05 band this replaces: a bound six hundred times tighter,
    // derived from the noise the record was generated with rather than from the
    // answer it produced. Realized ratios to the three-sigma bound: 0.10 and 0.56.
    Eigen::Matrix2d const covariance = second_moment.inverse();
    auto theta_hat = estimator.parameters();

    for (int p = 0; p < 2; ++p) {
        double const standard_error = noise_sd_fine * std::sqrt(covariance(p, p));
        CAPTURE(p, theta_hat(p), true_theta(p), standard_error);
        REQUIRE(std::abs(theta_hat(p) - true_theta(p))
                <= confidence_multiplier * standard_error);
    }
}

TEST_CASE("RLS with ill-conditioned regressor", "[rls][hardening][robustness]")
{
    auto estimator = ctrlpp::test::constructed(ctrlpp::rls<double, 2>::create());

    Eigen::Vector2d true_theta;
    true_theta << 1.0, 2.0;

    std::mt19937 gen(77);
    std::normal_distribution<double> noise(0.0, noise_sd_coarse);

    constexpr int samples = 200;
    constexpr double coupling = 1e-10;
    double second_moment = 0.0;

    for (int i = 0; i < samples; ++i) {
        // Ill-conditioned: second regressor element is 1e-10 * first
        double x = static_cast<double>(i) * 0.01;
        Eigen::Vector2d phi;
        phi << x, x * coupling;
        double y = true_theta.dot(phi) + noise(gen);
        REQUIRE(estimator.update(y, phi).has_value());
        second_moment += x * x;
    }

    auto theta = estimator.parameters();

    // The regressor spans one direction only, so the record identifies exactly
    // one combination and leaves the orthogonal one unexcited. Finiteness said
    // nothing about either half.
    //
    // The identifiable combination is the projection onto the regressor
    // direction, which the coupling makes indistinguishable from the first
    // parameter alone; its standard error is the noise standard deviation over
    // the square root of the accumulated second moment. Realized ratio to the
    // three-sigma bound: 0.09.
    double const standard_error = noise_sd_coarse / std::sqrt(second_moment);
    double const identifiable = theta(0) + coupling * theta(1);
    double const true_identifiable = true_theta(0) + coupling * true_theta(1);
    CAPTURE(identifiable, true_identifiable, standard_error);
    REQUIRE(std::abs(identifiable - true_identifiable)
            <= confidence_multiplier * standard_error);

    // The unexcited direction is not free to wander: every increment is a
    // multiple of the covariance applied to the regressor, so the estimate stays
    // proportional to the regressor's own component ratio. It deviates from that
    // proportionality only through the covariance recursion's own rounding, one
    // per operation of each update. Counting the update -- four for the
    // prediction error, six for the covariance-regressor product, four for the
    // denominator, two for the gain, four for the parameter step, twelve for the
    // covariance step, eight for the symmetrization and one for the trace, that
    // is forty one for two parameters -- over two hundred updates bounds it.
    // Realized: 820 units in the last place against a budget of 8200.
    constexpr int rls_update_ops = 41;
    double const proportionality_budget =
        static_cast<double>(rls_update_ops * samples) * eps * std::abs(theta(0) * coupling);
    CAPTURE(theta(0), theta(1), proportionality_budget);
    REQUIRE(std::abs(theta(1) - coupling * theta(0)) <= proportionality_budget);
}

// ── ARX hardening ──────────────────────────────────────────────────────────────

TEST_CASE("Batch ARX rejects a record shorter than the model order",
          "[arx][hardening][negative]")
{
    // The routine builds one regressor row per sample beyond max(NA, NB), so a
    // sample count at or below that order leaves no rows at all. Below it the
    // row count is computed by an unsigned subtraction, and at it the fit is
    // built from an empty regressor. Both are rejected before any index
    // arithmetic runs.
    SECTION("strictly fewer samples than the model order")
    {
        // 2 samples against max(NA, NB) = 3.
        Eigen::RowVectorXd Y(2);
        Y << 1.0, 2.0;
        Eigen::RowVectorXd U(2);
        U << 0.5, 1.0;

        auto result = ctrlpp::batch_arx<2, 3>(Y, U);
        REQUIRE(!result.has_value());
        CHECK(result.error() == ctrlpp::sysid_error::too_few_samples);
    }

    SECTION("exactly as many samples as the model order")
    {
        // 3 samples against max(NA, NB) = 3: zero regressor rows.
        Eigen::RowVectorXd Y(3);
        Y << 1.0, 2.0, 3.0;
        Eigen::RowVectorXd U(3);
        U << 0.5, 1.0, 1.5;

        auto result = ctrlpp::batch_arx<2, 3>(Y, U);
        REQUIRE(!result.has_value());
        CHECK(result.error() == ctrlpp::sysid_error::too_few_samples);
    }
}

TEST_CASE("Batch ARX rejects records of differing length",
          "[arx][hardening][negative]")
{
    Eigen::RowVectorXd Y(10);
    Y.setLinSpaced(10, 0.0, 1.0);
    Eigen::RowVectorXd U(8);
    U.setLinSpaced(8, 0.0, 1.0);

    auto result = ctrlpp::batch_arx<1, 1>(Y, U);
    REQUIRE(!result.has_value());
    CHECK(result.error() == ctrlpp::sysid_error::record_length_mismatch);
}

TEST_CASE("Batch ARX rejects a record that is not a single row",
          "[arx][hardening][negative]")
{
    // The routine reads only row zero of each record, so a two-row record would
    // silently identify from half its data.
    Eigen::MatrixXd Y = Eigen::MatrixXd::Zero(2, 10);
    Eigen::MatrixXd U = Eigen::MatrixXd::Zero(2, 10);

    auto result = ctrlpp::batch_arx<1, 1>(Y, U);
    REQUIRE(!result.has_value());
    CHECK(result.error() == ctrlpp::sysid_error::record_not_single_row);
}

TEST_CASE("Batch ARX rejects a non-finite sample", "[arx][hardening][negative]")
{
    SECTION("a NaN in the output record")
    {
        Eigen::RowVectorXd Y = Eigen::RowVectorXd::Zero(20);
        Eigen::RowVectorXd U = Eigen::RowVectorXd::Zero(20);
        Y(7) = std::numeric_limits<double>::quiet_NaN();

        auto result = ctrlpp::batch_arx<1, 1>(Y, U);
        REQUIRE(!result.has_value());
        CHECK(result.error() == ctrlpp::sysid_error::non_finite_sample);
    }

    SECTION("an infinity in the input record")
    {
        Eigen::RowVectorXd Y = Eigen::RowVectorXd::Zero(20);
        Eigen::RowVectorXd U = Eigen::RowVectorXd::Zero(20);
        U(3) = std::numeric_limits<double>::infinity();

        auto result = ctrlpp::batch_arx<1, 1>(Y, U);
        REQUIRE(!result.has_value());
        CHECK(result.error() == ctrlpp::sysid_error::non_finite_sample);
    }
}

TEST_CASE("Batch ARX identifies known AR/X coefficients", "[arx][hardening][convergence]")
{
    // Generate data from known ARX(1,1): y(t) = 0.7*y(t-1) + 0.3*u(t-1)
    constexpr int N = 500;
    Eigen::RowVectorXd Y(N);
    Eigen::RowVectorXd U(N);

    constexpr double true_a = 0.7;
    constexpr double true_b = 0.3;

    std::mt19937 gen(42);
    std::normal_distribution<double> noise(0.0, noise_sd_fine);
    std::uniform_real_distribution<double> input(-1.0, 1.0);

    Y(0) = 0.0;
    U(0) = input(gen);
    for (int t = 1; t < N; ++t) {
        U(t) = input(gen);
        Y(t) = true_a * Y(t - 1) + true_b * U(t - 1) + noise(gen);
    }

    auto result = ctrlpp::batch_arx<1, 1>(Y, U);
    REQUIRE(result.has_value());

    // The case name promises the coefficients, so the coefficients are asserted.
    // Their standard errors come from the same least-squares covariance the fit
    // itself carries: the noise standard deviation times the square root of the
    // corresponding diagonal entry of the inverse regressor second moment, which
    // is 1.7e-4 and 7.8e-5 here. Realized ratios to the three-sigma bound: 0.51
    // and 0.001.
    constexpr int rows = N - 1;
    Eigen::Matrix2d second_moment = Eigen::Matrix2d::Zero();
    for (int t = 1; t < N; ++t) {
        Eigen::Vector2d phi;
        phi << Y(t - 1), U(t - 1);
        second_moment += phi * phi.transpose();
    }
    Eigen::Matrix2d const covariance = second_moment.inverse();

    double const se_a = noise_sd_fine * std::sqrt(covariance(0, 0));
    double const se_b = noise_sd_fine * std::sqrt(covariance(1, 1));
    CAPTURE(result->system.A(0, 0), result->system.B(0, 0), se_a, se_b);
    REQUIRE(std::abs(result->system.A(0, 0) - true_a) <= confidence_multiplier * se_a);
    REQUIRE(std::abs(result->system.B(0, 0) - true_b) <= confidence_multiplier * se_b);

    // The fit metric's floor is derived, not chosen. The noise here enters the
    // RECURSION, so a free-run simulation from the identified model carries it
    // through the same pole and its standard deviation is amplified by one over
    // the square root of one minus the pole squared. Dividing that by the
    // centered-output norm the metric normalizes against gives 5.45e-3 -- and the
    // realized value is 5.58e-3, within two and a half percent of a bound derived
    // with no reference to it. The 0.1 it replaces was eighteen times looser.
    auto const fit_window = Y.segment(1, rows);
    double const centered_norm =
        std::sqrt((fit_window.array() - fit_window.mean()).square().sum());
    double const nrmse_floor = noise_sd_fine * std::sqrt(static_cast<double>(rows))
                               / (std::sqrt(1.0 - true_a * true_a) * centered_norm);

    CAPTURE(result->metrics.nrmse, nrmse_floor);
    REQUIRE(result->metrics.nrmse <= nrmse_floor * (1.0 + residual_norm_allowance(rows)));
}

TEST_CASE("Batch ARX with rank-deficient regressors", "[arx][hardening][negative]")
{
    // Constant input and output -- rank-deficient regressor matrix
    constexpr int N = 50;
    Eigen::RowVectorXd Y = Eigen::RowVectorXd::Constant(N, 1.0);
    Eigen::RowVectorXd U = Eigen::RowVectorXd::Constant(N, 1.0);

    auto result = ctrlpp::batch_arx<2, 1>(Y, U);
    REQUIRE(result.has_value());
    // Rank deficiency is not a domain violation: the record is well formed, so
    // the routine identifies and the least-squares solve resolves the deficient
    // directions to finite values.

    // Which member of the solution set it lands on is deliberately NOT pinned,
    // and the reason is a measurement rather than a preference: the decomposition
    // does not select the minimum-norm solution. The three coefficients that
    // reproduce this record are every triple summing to one, whose minimum-norm
    // member is one third each; the routine returns (0, 1, 0) instead. Naming the
    // minimum-norm choice as the contract would state something false, and
    // pinning the realized triple would pin the decomposition rather than the
    // identification.
    //
    // What every member of the solution set shares is that it reproduces the
    // record exactly, and that is what is asserted. Finiteness held for triples
    // that do not.
    //
    // With every sample of both records equal to one, a triple predicts the next
    // sample exactly when its three coefficients sum to one. Two additions stand
    // behind that sum on the test side; measured, it lands on one bitwise.
    constexpr int coefficient_sum_ops = 2;
    double const a1 = result->system.A(0, 0);
    double const a2 = result->system.A(1, 0);
    double const b1 = result->system.B(0, 0);
    CAPTURE(a1, a2, b1);
    REQUIRE(std::abs((a1 + a2 + b1) - 1.0) <= coefficient_sum_ops * eps);

    // The reported metrics are pinned too, because their disagreement is real
    // and worth stating rather than leaving for a reader to rediscover. The fit
    // metrics are computed from a free run started at a ZERO initial state, and
    // this record starts at one, so the simulated output is identically zero
    // while the record is identically one: a constant offset of exactly one at
    // every sample. The variance-accounted-for is blind to a constant offset and
    // reports a hundred percent; the normalized error divides by the record's
    // centered norm, which is exactly zero here, and reports infinity. Both are
    // their own definitions applied correctly, and asserting them is what stops
    // either being mistaken for a statement about the identification.
    REQUIRE(std::isinf(result->metrics.nrmse));
    REQUIRE(result->metrics.vaf == 100.0);
}

// ── MOESP hardening ────────────────────────────────────────────────────────────

TEST_CASE("MOESP on a record with no underlying system", "[moesp][hardening][negative]")
{
    // Purely random noise data -- no underlying system
    constexpr int N = 100;
    Eigen::RowVectorXd Y(N);
    Eigen::RowVectorXd U(N);

    std::mt19937 gen(99);
    std::normal_distribution<double> dist(0.0, noise_sd_fine);

    for (int i = 0; i < N; ++i) {
        Y(i) = dist(gen);
        U(i) = dist(gen);
    }

    auto sv = ctrlpp::moesp_singular_values(Y, U);

    // The count is structural, not merely positive. The routine takes the block
    // row count as the smaller of a quarter of the record and thirty, so twenty
    // five here, and the projected observability matrix has one row per block
    // row for a single-output record. A thin decomposition of a twenty five by
    // fifty one matrix therefore reports exactly twenty five singular values.
    constexpr Eigen::Index block_rows = N / 4;
    REQUIRE(sv.size() == block_rows);

    // What "near-zero singular values" means here is that they are the noise and
    // nothing else, and that is checkable exactly rather than against a chosen
    // magnitude: the Hankel assembly and the projection are linear in the record
    // and the singular values are absolutely homogeneous, so scaling the record
    // by a power of two must scale every singular value by exactly that factor,
    // with no rounding anywhere. Measured: bitwise identical.
    constexpr double exact_scale = 8.0;
    Eigen::RowVectorXd Y_scaled = exact_scale * Y;
    Eigen::RowVectorXd U_scaled = exact_scale * U;
    auto sv_scaled = ctrlpp::moesp_singular_values(Y_scaled, U_scaled);
    REQUIRE(sv_scaled.size() == sv.size());
    for (Eigen::Index k = 0; k < sv.size(); ++k) {
        CAPTURE(k, sv(k), sv_scaled(k));
        REQUIRE(sv_scaled(k) == exact_scale * sv(k));
    }

    // The spectrum carries no leading gap: the largest step between consecutive
    // singular values is not the first one, so no model order stands out and the
    // record has no recoverable structure. Stated as a comparison between the
    // routine's own numbers, it needs no threshold at all. The identifiable
    // fixture below asserts the same quantity with the opposite outcome.
    REQUIRE(largest_singular_value_gap(sv) != 0);

    auto result = ctrlpp::moesp<2>(Y, U);

    // The single fact the old disjunction refused to state. It accepted every
    // double except a not-a-number, so it held whichever way the routine went,
    // and it is invisible to a search for the not-a-number spelling of the same
    // defect because it is written with the infinity test instead.
    //
    // Determined by running: the identification SUCCEEDS on this record and
    // reports a finite condition number of 1.0239. The documented failure
    // contract -- an infinite condition number and a zeroed system -- is
    // therefore not what happens here, and the case below is the one that
    // exercises it.
    REQUIRE(std::isfinite(result.condition_number));
    REQUIRE_FALSE(result.system.A.isZero(0.0));

    // And the field means what the header says it means: it is the ratio of the
    // largest singular value to the last one the requested order consumes. Read
    // off the same decomposition, that is an exact identity, not an
    // approximation.
    REQUIRE(result.condition_number == sv(0) / sv(1));
    REQUIRE(result.condition_number >= 1.0);

    // Deliberately not asserted: that the identified model is meaningless. Saying
    // so numerically needs a rank threshold for a random Hankel matrix, and
    // deriving one is its own piece of numerical work rather than something to
    // pick. The homogeneity and the absent leading gap above are what can be
    // decided without it.
}

TEST_CASE("MOESP degenerate data returns a zeroed system", "[moesp][hardening][negative]")
{
    // The documented failure contract (docs/api/sysid/moesp.md) is that a
    // failed identification reports condition_number = infinity and hands back
    // zeroed system matrices. discrete_state_space is an aggregate of Eigen
    // fixed-size matrices whose default constructor leaves coefficients
    // uninitialized, so omitting members yields indeterminate values unless the
    // zeroing is explicit -- this pins that it is.
    constexpr int N = 64;
    Eigen::RowVectorXd Y = Eigen::RowVectorXd::Zero(N);
    Eigen::RowVectorXd U = Eigen::RowVectorXd::Zero(N);

    auto result = ctrlpp::moesp<2>(Y, U);

    REQUIRE(std::isinf(result.condition_number));
    REQUIRE(result.system.A.isZero(0.0));
    REQUIRE(result.system.B.isZero(0.0));
    REQUIRE(result.system.C.isZero(0.0));
    REQUIRE(result.system.D.isZero(0.0));
}

TEST_CASE("MOESP with wrong model order", "[moesp][hardening][negative]")
{
    // True system is first order, identify with NX=4
    constexpr int N = 300;
    Eigen::RowVectorXd Y(N);
    Eigen::RowVectorXd U(N);

    std::mt19937 gen(123);
    std::uniform_real_distribution<double> input(-1.0, 1.0);
    std::normal_distribution<double> noise(0.0, noise_sd_coarse);

    double x = 0.0;
    for (int t = 0; t < N; ++t) {
        U(t) = input(gen);
        Y(t) = x + noise(gen);
        x = 0.8 * x + 0.5 * U(t);
    }

    auto result = ctrlpp::moesp<4>(Y, U);

    // An over-specified order must still FIT, which is more than finiteness: the
    // surplus modes have nothing to explain, so the residual is still the
    // measurement noise. That noise sits on the output only and does not enter
    // the recursion, so a free run does not amplify it and the floor is the noise
    // standard deviation over the centered-output norm, unamplified -- the
    // opposite of the recursive record above, where it is amplified. Realized
    // ratio to the derived floor: 1.05.
    double const centered_norm = std::sqrt((Y.array() - Y.mean()).square().sum());
    double const nrmse_floor =
        noise_sd_coarse * std::sqrt(static_cast<double>(N)) / centered_norm;
    CAPTURE(result.metrics.nrmse, nrmse_floor);
    REQUIRE(result.metrics.nrmse <= nrmse_floor * (1.0 + residual_norm_allowance(N)));

    // The true order is still recoverable from the spectrum, which is what makes
    // the over-specification harmless: the largest step down between consecutive
    // singular values sits at the front, so one mode stands above the noise and
    // the rest are at it. The noise-only fixture above asserts the same quantity
    // and gets the opposite answer.
    auto sv = ctrlpp::moesp_singular_values(Y, U);
    REQUIRE(largest_singular_value_gap(sv) == 0);

    // And the reported condition number is that spectrum read at the requested
    // order, exactly.
    REQUIRE(result.condition_number == sv(0) / sv(3));
}

TEST_CASE("MOESP identifies known state-space system", "[moesp][hardening][convergence]")
{
    // True system: x(t+1) = 0.9*x(t) + 0.5*u(t), y(t) = x(t)
    constexpr int N = 500;
    Eigen::RowVectorXd Y(N);
    Eigen::RowVectorXd U(N);

    constexpr double true_pole = 0.9;
    constexpr double true_input_gain = 0.5;

    std::mt19937 gen(42);
    std::uniform_real_distribution<double> input(-1.0, 1.0);
    std::normal_distribution<double> noise(0.0, noise_sd_coarse);

    double x = 0.0;
    for (int t = 0; t < N; ++t) {
        U(t) = input(gen);
        Y(t) = x + noise(gen);
        x = true_pole * x + true_input_gain * U(t);
    }

    auto result = ctrlpp::moesp<1>(Y, U);

    // The case name promises identification and only a fit metric was asserted.
    // The coefficients themselves CANNOT be compared with the ones that generated
    // the record: the subspace method recovers the state basis from a singular
    // value decomposition, so it returns a similarity-transformed realization and
    // its A, B, C, D differ from the generating ones by an invertible change of
    // coordinates. Here the realized input coupling is 0.202 against a commanded
    // 0.5, and the output coupling absorbs the difference.
    //
    // What survives a similarity transform is what is asserted: the eigenvalue,
    // and the direct-current gain C (I - A)^-1 B + D.
    double const centered_norm = std::sqrt((Y.array() - Y.mean()).square().sum());
    double const signal_sd = centered_norm / std::sqrt(static_cast<double>(N));

    // Conservative by construction, and recorded as such: the bound is the
    // standard error of a single-regressor least-squares estimate at this noise,
    // this signal magnitude and this sample count. The subspace estimator uses
    // thirty block rows and is more efficient than that, but its own asymptotic
    // variance has not been derived here, so the simpler bound is used and its
    // realized margin is stated. Realized ratios to the three-sigma bound: 0.013
    // for the eigenvalue and 0.006 for the gain.
    double const parameter_se =
        noise_sd_coarse / (signal_sd * std::sqrt(static_cast<double>(N)));

    double const pole = result.system.A(0, 0);
    CAPTURE(pole, parameter_se);
    REQUIRE(std::abs(pole - true_pole) <= confidence_multiplier * parameter_se);

    // The gain amplifies a pole error by one over one minus the pole, so its
    // bound carries that amplification rather than repeating the parameter one.
    double const true_dc_gain = true_input_gain / (1.0 - true_pole);
    double const dc_gain =
        result.system.C(0, 0) * result.system.B(0, 0) / (1.0 - pole) + result.system.D(0, 0);
    double const dc_gain_se = parameter_se * true_dc_gain / (1.0 - true_pole);
    CAPTURE(dc_gain, true_dc_gain, dc_gain_se);
    REQUIRE(std::abs(dc_gain - true_dc_gain) <= confidence_multiplier * dc_gain_se);

    // The fit metric keeps its place with a derived floor: measurement noise on
    // the output, unamplified by the free run, over the centered-output norm.
    // Realized ratio: 1.06, against the 0.15 this replaces.
    double const nrmse_floor =
        noise_sd_coarse * std::sqrt(static_cast<double>(N)) / centered_norm;
    CAPTURE(result.metrics.nrmse, nrmse_floor);
    REQUIRE(result.metrics.nrmse <= nrmse_floor * (1.0 + residual_norm_allowance(N)));

    // At a requested order of one the condition number is the leading singular
    // value over itself, so it is exactly one whatever the record is. Pinning it
    // says the field is the ratio the header describes and not something else.
    REQUIRE(result.condition_number == 1.0);
}

TEST_CASE("Recursive ARX order 2 to_state_space superdiagonal",
          "[recursive_arx][hardening][coverage]")
{
    // NA=2 exercises the superdiagonal initialization loop in to_state_space()
    auto arx = ctrlpp::test::constructed(ctrlpp::recursive_arx<double, 2, 1>::create());

    std::mt19937 gen(42);
    std::uniform_real_distribution<double> input(-1.0, 1.0);

    double y = 0.0, y_prev = 0.0;
    double u_prev = 0.0;
    for (int t = 0; t < 500; ++t) {
        double u = input(gen);
        double y_new = 0.6 * y + 0.2 * y_prev + 0.3 * u_prev;
        REQUIRE(arx.update(y_new, u).has_value());
        y_prev = y;
        y = y_new;
        u_prev = u;
    }

    auto ss = arx.to_state_space();
    // 2nd-order system: A is 2x2 with superdiagonal entry.
    //
    // The superdiagonal of a companion form is structurally one, not merely
    // finite. That is the whole content of the initialization loop the case says
    // it exercises, and finiteness passed for every value the loop could have
    // written -- including the zero it writes if the loop never runs, which is
    // exactly the defect the case was created to catch.
    REQUIRE(ss.A(0, 1) == 1.0);
    REQUIRE(ss.A(1, 1) == 0.0);
    REQUIRE(ss.A.rows() == 2);
}
